name: 2.a. Build & Deploy Project

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ldes-server
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  DOCKER_HUB_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
  DEPLOY_PACKAGE_TO_OSSRH: ${{ vars.DEPLOY_PACKAGE_TO_OSSRH }}
  ANALYSE_PACKAGE: ${{ vars.ANALYSE_PACKAGE }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION }}
  JAVA_VERSION: ${{ vars.JAVA_VERSION }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.determine-version.outputs.version }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Java with GPG private key
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') == true || fromJSON(env.ANALYSE_PACKAGE || 'false') == true }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set up Java
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') != true }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache SonarCloud packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Determine version
        id: determine-version
        run: |
          export VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Analyse package and publish Sonar Cloud analysis
        if: ${{ fromJSON(env.ANALYSE_PACKAGE || 'false') == true }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Pcoverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Create package
        if: ${{ fromJSON(env.ANALYSE_PACKAGE || 'false') != true }}
        run: |
          mvn -B verify
      - name: Publish package
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') == true }}
        run: |
          mvn deploy -DskipTests -Dmaven.javadoc.skip=true -B -P release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Upload JARs
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: artifacts
          path: |
            **/*with-dependencies.jar
            **/*application.jar
  create-image:
    # If the branch is main, we push to DockerHub, otherwise to the GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Download JARs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: .github
      - name: Define docker variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=${{ needs.build.outputs.version }}" >> $GITHUB_ENV
            echo "IMAGES=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
            if [[ "${{ needs.build.outputs.version }}" != *"SNAPSHOT"* ]]; then
              echo "LATEST=latest" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=${{ needs.build.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
            echo "IMAGES=${{ env.GHCR_REGISTRY }}/${{ github.repository }}" >> $GITHUB_ENV
            echo "LATEST=latest" >> $GITHUB_ENV
          fi
      - name: Log in to the DockerHub Container registry
        if: github.ref_name == 'main'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to the GitHub Container registry
        if: github.ref_name != 'main'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=raw,value=${{env.IMAGE_TAG}}
            type=raw,value=${{env.LATEST}}
      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .github
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
