name: 2.a. Build & Deploy Project

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ldes-server
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  DOCKER_HUB_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}
  DEPLOY_PACKAGE_TO_OSSRH: ${{ vars.DEPLOY_PACKAGE_TO_OSSRH }}
  ANALYSE_PACKAGE: ${{ vars.ANALYSE_PACKAGE }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION }}
  JAVA_VERSION: ${{ vars.JAVA_VERSION }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.determine-version.outputs.version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Java with GPG private key
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') == true || fromJSON(env.ANALYSE_PACKAGE || 'false') == true }}
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Set up Java
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') != true }}
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache SonarCloud packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Determine version
        id: determine-version
        run: |
          export VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Analyse package and publish Sonar Cloud analysis
        if: ${{ fromJSON(env.ANALYSE_PACKAGE || 'false') == true }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Pcoverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Create package
        if: ${{ fromJSON(env.ANALYSE_PACKAGE || 'false') != true }}
        run: |
          mvn -B verify
      - name: Publish package
        if: ${{ fromJSON(env.DEPLOY_PACKAGE_TO_OSSRH || 'false') == true }}
        run: |
          mvn deploy -DskipTests -Dmaven.javadoc.skip=true -B -P release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Upload JARs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: |
            **/*with-dependencies.jar
            **/*application.jar
  create-image:
    # If the branch is main, we push to DockerHub, otherwise to the GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Download JARs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: .github
      - name: Define docker variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=${{ needs.build.outputs.version }}" >> $GITHUB_ENV
            echo "IMAGES=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
            if [[ "${{ needs.build.outputs.version }}" != *"SNAPSHOT"* ]]; then
              echo "LATEST=latest" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=${{ needs.build.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
            echo "IMAGES=${{ env.GHCR_REGISTRY }}/${{ github.repository }}" >> $GITHUB_ENV
            echo "LATEST=latest" >> $GITHUB_ENV
          fi
      - name: Log in to the DockerHub Container registry
        if: github.ref_name == 'main'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to the GitHub Container registry
        if: github.ref_name != 'main'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=raw,value=${{env.IMAGE_TAG}}
            type=raw,value=${{env.LATEST}}
      - name: Build and push Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .github
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
