name: 4. Prepare New Version for Project

on:
  workflow_dispatch:
    inputs:
      type_of_bump:
        type: choice
        description: Type of version bump
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Release
        uses: qcastel/github-actions-maven-release@f0dbe4b1c14ba8df1dd07d471e4abcec2cb94399 # v1.12.44
        with:
          git-release-bot-name: "Maven Release"
          git-release-bot-email: "maven@release.io"
          version-patch: ${{ github.event.inputs.type_of_bump == 'patch' }}
          version-minor: ${{ github.event.inputs.type_of_bump == 'minor' }}
          version-major: ${{ github.event.inputs.type_of_bump == 'major' }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true -Dskipdeploy=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          release-branch-name: 'develop'
